---
# Github action for running unittests with GTest and MKL library
name: unittest-gtest-mkl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Testing dependences
      run: sudo apt-get install libgtest-dev intel-mkl

    # Checkout code
    - uses: actions/checkout@v1

    - name: Build binary
      run: mkdir build && cd build && cmake .. && make

    - name: Run binary
      run: cd build && ./bin/using_mkl
    
    - name: Run tests
      run: cd build && ctest
...
